### ISSUE TITLE
파일 구성 변경

### ISSUE THREAD

**Issue by AnSuebin** [tamnaye/frontend#167]
---
name: "Issue: \U0001F48ERefactor"
about: Refactor 작업 사항을 입력해주세요.
title: '파일 구성 변경'
labels: 'refactor'
assignees: '안수빈'

---

## Description
복잡성이 높은 코드를 파일 구성을 변경하여, 찾기 쉽도록 수정합니다.

## Before
한 페이지에 너무 많은 코드들이 섞여있습니다.

## After
코드를 찾는 것이 편할 뿐만 아니라 이로 인한 업무 능률도 오르게 됩니다.

## Todo
- [ ] 파일을 api / components / config / icons / pages / styles / types / utils 로 분리합니다.
- [ ] 페이지별로 component를 template 형태로 분리합니다.
- [ ] headless 형태를 추구합니다.
